-- MySQL Script generated by MySQL Workbench
-- Thu May 29 20:05:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pp_tecnico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pp_tecnico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pp_tecnico` DEFAULT CHARACTER SET utf8 ;
USE `pp_tecnico` ;

-- -----------------------------------------------------
-- Table `pp_tecnico`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pp_tecnico`.`login` (
  `idlogin` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `nome` VARCHAR(150) NULL,
  `permissao` VARCHAR(150) NULL,
  PRIMARY KEY (`idlogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pp_tecnico`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pp_tecnico`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(150) NULL,
  `contato` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pp_tecnico`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pp_tecnico`.`servico` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL,
  `valor` DOUBLE NULL,
  `servico` VARCHAR(150) NULL,
  `funcionario` VARCHAR(100) NULL,
  `status` VARCHAR(150) NULL,
  `data_abertura` DATE NULL,
  `data_fechamento` DATE NULL,
  `fk_login` INT NULL,
  `fk_cliente` INT NULL,
  PRIMARY KEY (`idvenda`),
  INDEX `servico_login_idx` (`fk_login` ASC),
  INDEX `servico_cliente_idx` (`fk_cliente` ASC),
  CONSTRAINT `servico_login`
    FOREIGN KEY (`fk_login`)
    REFERENCES `pp_tecnico`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servico_cliente`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `pp_tecnico`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
